# -*- coding: utf-8 -*-
"""
prepare_original.py

Prepares a build tree of the original version for one instance, ready for nvcc.

The original version has the instance, the population, the generations and the number of repetitions
compiled in, one settings file per instance, so comparing it against this version needs one build per
instance. This script produces that tree from a git ref (master by default, the original code line) and
makes three changes, each of which is needed for the comparison to measure the algorithm:

* The settings file is generated from the instance's own .dat, not taken from the repository. The
  settings_KC20_2fl_1rl.cu of the original version holds the matrices of KC20-2fl-2rl (bug B3), so a
  binary built from it solves a different problem than the one its name announces.
* cudaMalloc of the curand states is sized by the number of states the kernels write (bugs B1). Without
  this, CUDA 13.4 corrupts the NSGA-II buffers and the run reports impossible fitness values.
* binaryTournament is launched with one block per tournament, not per population row (bug B2).

Usage:
    python scripts/prepare_original.py KC20-2fl-1rl out/dir [--ref master]
                                       [--population 64] [--iterations 300] [--runs 30]

Copyright (C) 2019-2026 Andres Pupiales Arevalo <apupiales@gmail.com>
SPDX-License-Identifier: GPL-3.0-or-later
"""
import argparse
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# (description, unique text of the original, replacement). Each must appear exactly once.
MEMORY_FIXES = [
    ('B2: one block per tournament, not per population row',
     'binaryTournament <<<NSGA2_POPULATION_SIZE, 1 >>> (d_offspring, d_offspring_rank,',
     'binaryTournament <<<POPULATION_SIZE, 1 >>> (d_offspring, d_offspring_rank,'),
    ('B1: one curand state per tournament',
     'curandState* d_state;\n\tcudaMalloc(&d_state, sizeof(curandState));',
     'curandState* d_state;\n\tcudaMalloc(&d_state, POPULATION_SIZE * sizeof(curandState));'),
    ('B1: one curand state per thread of curand_setup',
     'curandState* d_state;\n\t\tcudaMalloc(&d_state, sizeof(curandState));',
     'curandState* d_state;\n\t\tcudaMalloc(&d_state, NSGA2_POPULATION_SIZE * 128 * sizeof(curandState));'),
]


def load_instance(path):
    """(n, objectives, distances transposed, flow matrices) exactly as src/instance.cpp reads them."""
    with open(path, encoding='utf-8') as f:
        head, rest = f.read().split('\n', 1)
    head = head.replace(':', ' ').replace('=', ' ').split()
    n = int(head[head.index('facilities') + 1])
    objectives = int(head[head.index('objectives') + 1])
    values = [int(v) for v in rest.split()]
    distances = values[:n * n]
    flows = [values[n * n * (k + 1):n * n * (k + 2)] for k in range(objectives)]
    # The original version keeps the distances transposed in constant memory.
    return n, objectives, [distances[b * n + a] for a in range(n) for b in range(n)], flows


def settings_source(instance, n, objectives, distances, flows, population, iterations):
    """The settings_*.cu of the original version for this instance."""
    def rows(values):
        return ',\n'.join('\t\t{%s}' % ', '.join(str(v) for v in values[r * n:(r + 1) * n]) for r in range(n))

    return '\n'.join([
        '/*',
        ' * Settings of the original version for %s, generated by scripts/prepare_original.py' % instance,
        ' * from mQAPData/%s.dat. Do not edit by hand.' % instance,
        ' * @see http://www.cs.bham.ac.uk/~jdk/mQAP/',
        ' */',
        '',
        '#define FACILITIES_LOCATIONS %d' % n,
        '#define OBJECTIVES %d' % objectives,
        '#define POPULATION_SIZE %d' % population,
        '#define ITERATIONS %d' % iterations,
        '#define EXCHANGE_MUTATION_PROBABILITY 1',
        '#define TRANSPOSITION_MUTATION_PROBABILITY 1',
        '',
        '__constant__ int d_transposeDistancesMatrix[FACILITIES_LOCATIONS][FACILITIES_LOCATIONS] =',
        '{',
        rows(distances),
        '};',
        '',
        '__constant__ int d_flowMatrices[OBJECTIVES][FACILITIES_LOCATIONS][FACILITIES_LOCATIONS] =',
        '{',
        ',\n'.join('\t{\n%s\n\t}' % rows(flow) for flow in flows),
        '};',
        '',
    ])


def patch(text, old, new, what):
    if text.count(old) != 1:
        sys.exit('%s: expected exactly one occurrence, found %d' % (what, text.count(old)))
    return text.replace(old, new)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('instance', help='instance name, e.g. KC20-2fl-1rl')
    parser.add_argument('out_dir', help='directory to write the build tree into')
    parser.add_argument('--ref', default='master', help='git ref holding the original version (default: master)')
    parser.add_argument('--population', type=int, default=64)
    parser.add_argument('--iterations', type=int, default=300)
    parser.add_argument('--runs', type=int, default=30, help='repetitions compiled in (TIMES)')
    args = parser.parse_args()

    if not os.path.isdir(args.out_dir):
        os.makedirs(args.out_dir)

    def show(path):
        return subprocess.run(['git', '-C', ROOT, 'show', '%s:%s' % (args.ref, path)],
                              check=True, capture_output=True).stdout.decode('utf-8', 'replace')

    kernel = show('kernel.cu').replace('\r\n', '\n')
    general = show('general_dev_settings.cu').replace('\r\n', '\n')

    for what, old, new in MEMORY_FIXES:
        kernel = patch(kernel, old, new, what)
        print('  applied %s' % what)

    include = re.search(r'(?m)^#include\s+"(settings_\w+\.cu)"', kernel)
    if not include:
        sys.exit('the active settings include was not found in kernel.cu of %s' % args.ref)
    kernel = kernel.replace('#include "%s"' % include.group(1), '#include "settings_generated.cu"')
    print('  settings include %s -> settings_generated.cu' % include.group(1))

    general = patch(general, '#define TIMES 1', '#define TIMES %d' % args.runs, 'repetitions (TIMES)')
    print('  TIMES = %d' % args.runs)

    n, objectives, distances, flows = load_instance(os.path.join(ROOT, 'mQAPData', args.instance + '.dat'))
    settings = settings_source(args.instance, n, objectives, distances, flows,
                               args.population, args.iterations)

    for name, text in (('kernel.cu', kernel), ('general_dev_settings.cu', general),
                       ('settings_generated.cu', settings)):
        with open(os.path.join(args.out_dir, name), 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
    print('  %s: n = %d, objectives = %d, P = %d, %d generations, %d repetitions -> %s'
          % (args.instance, n, objectives, args.population, args.iterations, args.runs, args.out_dir))


if __name__ == '__main__':
    main()
